[package]
name = "quyc_client"
version = "0.1.0"
edition = "2024"
description = "HTTP/3 client implementation with protocol support and connection management"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fluent-ai/fluent-ai"
keywords = ["http", "http3", "quic", "client", "protocol"]
categories = ["network-programming", "web-programming::http-client"]
authors = ["Fluent AI Team"]

[dependencies]
# Async streaming foundation
ystream = { git = "https://github.com/cyrup-ai/ystream.git", branch = "main" }

# HTTP foundation
http = "1"
url = "2"
urlencoding = "2"

# HTTP/2 support
h2 = "0.4.12"

# HTTP/3 / QUIC support
quiche = "0.24"

# TLS support
rustls = { version = "0.23", features = ["ring"] }
rustls-pemfile = "2"
webpki-roots = "1"
# DNS resolution
hickory-resolver = "0.25"

# Core utilities
tokio = { version = "1", features = ["full"] }
bytes = "1"
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["std", "alloc"] }
hyper = { version = "1", features = ["http1", "client"] }
hyper-util = { version = "0.1", features = ["http1", "http2", "client", "client-legacy"] }
pin-project-lite = "0.2"
once_cell = "1"

# Error handling
anyhow = "1"
thiserror = "2"

# Collections
hashbrown = "0.16"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"

# Documentation testing
doc-comment = "0.3"

# Core utilities
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }

# Atomic operations
crossbeam-channel = "0.5"
crossbeam-skiplist = "0.1"
crossbeam-utils = "0.8"

# TLS implementations
tokio-rustls = "0.26"
rustls-native-certs = "0.8"

# Native TLS support removed - using rustls universally

# Certificate generation and parsing
rcgen = { version = "0.14", features = ["pem", "x509-parser"] }
der = "0.8"
const-oid = { version = "0.10", features = ["db"] }
x509-certificate = "0.25"
x509-cert = "0.2"
x509-parser = "0.18"
x509-ocsp = "0.2"
spki = "0.7"
pem = "3"

# Cryptography
ring = "0.17"

# HTTP body handling
http-body = "1"
http-body-util = "0.1"

# Collections and data structures
dashmap = "6"
arrayvec = "0.7"

# Cookie handling
cookie = "0.18"
cookie_store = "0.22"

# Text processing
regex = "1"

# System utilities
hostname = "0.4"
socket2 = "0.6"

# Random number generation
fastrand = "2"

# Utilities
hex = "0.4"
rand = "0.9"
lazy_static = "1"
zeroize = "1"
keyring = "3"

# Sugars and utilities
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }

# Telemetry and stats
atomic = "0.6"

# Logging
log = "0.4"
tracing = "0.1"

[features]
default = ["h2", "h3", "__rustls"]
h2 = []
h3 = []
# default-tls feature removed - using rustls universally
__rustls = []
__tls = ["__rustls"]

[lib]
name = "quyc_client"
path = "src/lib.rs"
