[package]
name = "quyc"
version = "0.1.0"
edition = "2024"
description = "Zero-allocation HTTP/3 client with fluent builder pattern and streaming-first architecture"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fluent-ai/fluent-ai"
documentation = "https://docs.rs/quyc"
keywords = ["http", "http3", "quic", "streaming", "zero-allocation"]
categories = ["network-programming", "web-programming::http-client"]
authors = ["Fluent AI Team"]

[dependencies]
# Client implementation
quyc_client = { path = "../client" }

# Async streaming foundation
ystream = { git = "https://github.com/cyrup-ai/ystream.git", branch = "main" }

# HTTP foundation
http = "1"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"

# Base64 encoding for auth
base64 = "0.22"

# Collections
hashbrown = "0.16"

# Logging
log = "0.4"
tracing = "0.1"

# Bytes manipulation
bytes = "1"

# URL parsing
url = "2"

# Regex for validation
regex = "1"

# Async runtime for thread pool integration
tokio = { version = "1", features = ["full"] }

# Fluent interface patterns
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4"
axum = { version = "0.8", features = ["macros"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
rustls = { version = "0.23", features = ["aws-lc-rs"] }
chrono = "0.4"
env_logger = "0.11"

[[example]]
name = "fluent_builder"
path = "../../examples/fluent_builder.rs"


[features]
default = []

[lib]
name = "quyc"
path = "src/lib.rs"
