[profile.default]
# Run tests in parallel with optimal thread count
test-threads = "num-cpus"

# Timeout configuration
slow-timeout = { period = "60s", terminate-after = 2 }
leak-timeout = "100ms"

# Test output configuration
status-level = "pass"
final-status-level = "slow"

# Retry configuration for flaky tests
retries = 2

[profile.ci]
# CI-specific configuration
test-threads = 4
retries = 3
slow-timeout = { period = "120s", terminate-after = 1 }

[profile.quick]
# Quick test profile for development
test-threads = "num-cpus"
retries = 0
slow-timeout = { period = "30s", terminate-after = 1 }